name:                test-extensible
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/test-extensible#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Simple
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - cassava
  - cassava-conduit
  - constraints
  - extensible
  - lens
  - unordered-containers
  - vector
  - ghc-prim
  - text

executables:
  test-extensible:
    source-dirs:      src
    main:             Main.hs
